name: Build Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install python_package
      run: poetry install
    - name: Generate Docs
      run: |
        poetry run make gen-docs
        touch docs/build/html/.nojekyll
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: sphinx-docs # The branch the action should deploy to.
        FOLDER: docs/build/html/ # The folder the action should deploy.
