name: Docs

on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install python_package
      run: poetry install --extras=docs
    - name: Generate Docs
      run: |
        poetry run make gen-docs
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: sphinx-docs # The branch the action should deploy to.
        FOLDER: docs/build/html/ # The folder the action should deploy.
