name: Build and Release

on:
  push:
    tags:
    - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: ./.github/workflows/update_coverage.yaml

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/workflows/lint.yaml

  create-release:
    needs: [test, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1

  publish-docs:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install python_package
      run: poetry install --extras=docs
    - name: Generate Docs
      run: |
        poetry run make gen-docs
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: sphinx-docs # The branch the action should deploy to.
        FOLDER: docs/build/html/ # The folder the action should deploy.

  publish-package:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Build python_package
      run: poetry build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
