name: Test, Lint, and Upload Coverage Report

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: python_package/python_package/.github/workflows/test.yml


  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: python_package/python_package/.github/workflows/lint.yml
